FROM node:21-alpine as development

# Enviroment variables
ENV NODE_PORT=3000
ENV DIR=/usr/app

WORKDIR ${DIR}

COPY package*.json ./

COPY . .

# RUN npm install
RUN npm install -g npm@latest
RUN npm npm cache clean --force && npm install -g typescript

EXPOSE $NODE_PORT

CMD ["ts-node", "src/network.ts"]
#CMD ["node", "build/src/network.js"]
#CMD ["node", "build/app.js"]

FROM node:21-alpine as production

# Enviroment variables
ENV NODE_PORT=3000
ENV DIR=/usr/app

WORKDIR ${DIR}

COPY package*.json ./

COPY . .

# RUN npm install
RUN npm install -g npm@latest
RUN npm install rimraf --global
RUN npm install --only=production && npm cache clean --force && npm install -g typescript && npm install rimraf --save
RUN npm run build

EXPOSE $NODE_PORT

#CMD ["node", "build/src/network.js"]
CMD ["node", "build/app.js"]